
Due to MODULEPATH changes, the following have been reloaded:
  1) Python/3.12.3-GCCcore-13.3.0


Due to MODULEPATH changes, the following have been reloaded:
  1) CUDA/12.4.0

master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[W socket.cpp:426] [c10d] The server socket has failed to bind to [::]:29400 (errno: 98 - Address already in use).
[W socket.cpp:426] [c10d] The server socket has failed to bind to 0.0.0.0:29400 (errno: 98 - Address already in use).
[E socket.cpp:462] [c10d] The server socket has failed to listen on any local network address.
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:  25%|██▌       | 1/4 [00:58<02:55, 58.59s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:58<02:56, 58.79s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:58<02:56, 58.78s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:58<02:56, 58.82s/it]Loading checkpoint shards:  50%|█████     | 2/4 [01:56<01:56, 58.21s/it]Loading checkpoint shards:  50%|█████     | 2/4 [01:56<01:56, 58.30s/it]Loading checkpoint shards:  50%|█████     | 2/4 [01:56<01:56, 58.30s/it]Loading checkpoint shards:  50%|█████     | 2/4 [01:56<01:56, 58.32s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [03:00<01:00, 60.67s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [03:00<01:00, 60.75s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [03:00<01:00, 60.76s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [03:00<01:00, 60.80s/it]Loading checkpoint shards: 100%|██████████| 4/4 [03:12<00:00, 41.73s/it]Loading checkpoint shards: 100%|██████████| 4/4 [03:12<00:00, 48.24s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [03:13<00:00, 41.74s/it]Loading checkpoint shards: 100%|██████████| 4/4 [03:13<00:00, 48.26s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [03:13<00:00, 41.77s/it]Loading checkpoint shards: 100%|██████████| 4/4 [03:13<00:00, 48.26s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [03:13<00:00, 41.78s/it]Loading checkpoint shards: 100%|██████████| 4/4 [03:13<00:00, 48.26s/it]
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:  25%|██▌       | 1/4 [00:01<00:05,  1.81s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:01<00:05,  1.81s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:02<00:07,  2.45s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:02<00:07,  2.51s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:03<00:03,  1.77s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:03<00:03,  1.77s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:04<00:04,  2.48s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:05<00:05,  2.50s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:05<00:01,  1.76s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:05<00:01,  1.75s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:05<00:00,  1.27s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:05<00:00,  1.46s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:05<00:00,  1.27s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:05<00:00,  1.45s/it]
Loading checkpoint shards:  75%|███████▌  | 3/4 [00:06<00:02,  2.13s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:06<00:02,  2.12s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:07<00:00,  1.46s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:07<00:00,  1.78s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:07<00:00,  1.46s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:07<00:00,  1.78s/it]
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/s33zganj/LLaMA_SOTOPIA/pipeline.py", line 52, in <module>
  File "/home/s33zganj/LLaMA_SOTOPIA/pipeline.py", line 52, in <module>
  File "/home/s33zganj/LLaMA_SOTOPIA/pipeline.py", line 52, in <module>
  File "/home/s33zganj/LLaMA_SOTOPIA/pipeline.py", line 52, in <module>
        model = model.to(device)    model = model.to(device)
model = model.to(device)

  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2883, in to
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2883, in to
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2883, in to
    model = model.to(device)
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2883, in to
                return super().to(*args, **kwargs)return super().to(*args, **kwargs)
return super().to(*args, **kwargs)return super().to(*args, **kwargs)


  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
        return self._apply(convert)return self._apply(convert)

  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
        return self._apply(convert)return self._apply(convert)

  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
        module._apply(fn)module._apply(fn)

  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
        module._apply(fn)module._apply(fn)

    module._apply(fn)  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply

  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    module._apply(fn)
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    param_applied = fn(param)
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    module._apply(fn)
      [Previous line repeated 2 more times]
module._apply(fn)
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
  [Previous line repeated 2 more times]
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 79.19 GiB total capacity; 22.33 GiB already allocated; 9.62 MiB free; 22.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    param_applied = fn(param)
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
        param_applied = fn(param)param_applied = fn(param)

  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 79.19 GiB total capacity; 22.33 GiB already allocated; 9.62 MiB free; 22.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 79.19 GiB total capacity; 15.02 GiB already allocated; 9.62 MiB free; 15.02 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 224.00 MiB (GPU 0; 79.19 GiB total capacity; 15.55 GiB already allocated; 201.62 MiB free; 15.55 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3193044) of binary: /home/s33zganj/pytorch/bin/python
Traceback (most recent call last):
  File "/home/s33zganj/pytorch/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/s33zganj/pytorch/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/s33zganj/LLaMA_SOTOPIA/pipeline.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-09-10_15:54:55
  host      : node-05.bender
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3193045)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-09-10_15:54:55
  host      : node-05.bender
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 3193046)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-09-10_15:54:55
  host      : node-05.bender
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 3193047)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-10_15:54:55
  host      : node-05.bender
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3193044)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: node-05: task 0: Exited with exit code 1
